# Rules
#  https://bazel.build/rules

workspace(name = "start-cpp20")

# ------------------------------------------------------------------------------
# Embedded non-native rules
#  https://bazel.build/rules#embedded-rules
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# ------------------------------------------------------------------------------
# Toolchain for LLVM
#  https://github.com/grailbio/bazel-toolchain
BAZEL_TOOLCHAIN_TAG = "0.7.2"
BAZEL_TOOLCHAIN_SHA = "f7aa8e59c9d3cafde6edb372d9bd25fb4ee7293ab20b916d867cd0baaa642529"

http_archive(
    name = "com_grail_bazel_toolchain",
    sha256 = BAZEL_TOOLCHAIN_SHA,
    strip_prefix = "bazel-toolchain-{tag}".format(tag = BAZEL_TOOLCHAIN_TAG),
    canonical_id = BAZEL_TOOLCHAIN_TAG,
    url = "https://github.com/grailbio/bazel-toolchain/archive/{tag}.tar.gz".format(tag = BAZEL_TOOLCHAIN_TAG),
)

load("@com_grail_bazel_toolchain//toolchain:deps.bzl", "bazel_toolchain_dependencies")

bazel_toolchain_dependencies()

load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "14.0.0",
)

load("@llvm_toolchain//:toolchains.bzl", "llvm_register_toolchains")

llvm_register_toolchains()

# ------------------------------------------------------------------------------
# Skylib, for manipulating collections, file paths, ...
#  https://github.com/bazelbuild/bazel-skylib
git_repository(
    name = "bazel_skylib",
    commit = "ee67264452174896741824ed25ade0f6d58ca642",  # 1.2.1
    remote = "http://github.com/bazelbuild/bazel-skylib"
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

# ------------------------------------------------------------------------------
# rules_cc_module, to use C++20 modules
#  https://github.com/rnburn/rules_cc_module
# git_repository(
#     name = "com_github_rnburn_bazel_cpp20_modules",
#     commit = "0ce4752384fcf0eb903aedaa4dbc8102862d5c21",
#     remote = "https://github.com/rnburn/rules_cc_module"
# )
